Sentry set up
digi-serve/ab_service_api_sails pull request #106
Opened 2023-09-26 07:32 UTC by nh758

See https://github.com/digi-serve/ab-utils/pull/56 (requires merging and updating ab-utils before this works)

## Release Notes

- set up sentry tracking for api

2023-09-26 08:15 UTC, joshAppDev approved these changes

2023-09-27 20:30 UTC, Hiro-Nakamura requested changes
Just one question about ENV variables, then good to go!

2023-09-27 20:30 UTC, Hiro-Nakamura commented on app_waitMysql.js
> +   dsn: "https://0363fe8e68b2fbd38a807305a3a1212c@o144358.ingest.sentry.io/4505945407488000",
Should this be passed in using our ENV variables?  
```
const AB = require("@digiserve/ab-utils");
const env = AB.defaults.env;

... 
Sentry.init({
dsn: env("SENTRY_DSN"),

```

Should we have the option for other implementations to have separate Sentry configs than us.

2023-10-06 03:08 UTC, joshAppDev approved these changes

2023-10-23 18:10 UTC, Hiro-Nakamura approved these changes
LGTM

2023-10-27 05:15 UTC, merged