Service Reset Password URL
digi-serve/ab_service_api_sails pull request #5
Opened 2022-05-03 05:07 UTC by guyyoo

Add the new param "url"

2022-05-04 07:36 UTC, wongpratan approved these changes

2022-05-05 08:42 UTC, Hiro-Nakamura requested changes
The input validations are our own shorthand for using the `joi.dev`  validation framework.  Check their site for more validation options on the types of inputs we are validating.

2022-05-05 08:42 UTC, Hiro-Nakamura commented on api/controllers/tenant_manager/tenant-add.js
> +   url: { string: true, required: true },
try to change this to:
` url: { string: {uri: true}, required: true},`

So we make sure it is a valid uri  and not some random string.

2022-05-10 02:42 UTC, Hiro-Nakamura approved these changes
LGTM

2022-05-10 03:30 UTC, merged